In [1]:
#Import dependencies
import pandas as pd

In [2]:
#Read all movies csv
all_movies = pd.read_csv("output_data/merged.csv")

In [3]:
#Check for discrepancies
print(len(all_movies))
print(all_movies["Title"].nunique())

977
974

In [4]:
#Find and display duplicate movie titles
duplicates = all_movies[all_movies.duplicated(["Title"])]["Title"].unique()
duplicates

array(['All Together Now', 'Cats', 'Lost Girls'], dtype=object)

In [5]:
#Display all rows for duplicate movie titles
dupes_df = all_movies.loc[all_movies["Title"].isin(duplicates),:]
dupes_df

,Title,Year,Released,Runtime,Genre,Awards,Metascore,imdbRating,imdbVotes,imdbID,BoxOffice,Language,budget_max,budget_min
498,Cats,2019,20 Dec 2019,110 min,"Comedy, Drama, Family",11 wins & 8 nominations,32.0,2.8,"52,975",tt5697572,"$27,166,770",English,95000000.0,0.0
553,Lost Girls,2020,13 Mar 2020,95 min,"Crime, Drama, Mystery",1 win,67.0,6.1,"22,875",tt3111426,NaN,English,0.0,0.0
645,All Together Now,2020,28 Aug 2020,92 min,Drama,NaN,64.0,6.5,"4,719",tt3155342,NaN,English,0.0,0.0
649,All Together Now,2020,28 Aug 2020,92 min,Drama,NaN,64.0,6.5,"4,719",tt3155342,NaN,English,0.0,0.0
661,Cats,2019,20 Dec 2019,110 min,"Comedy, Drama, Family",11 wins & 8 nominations,32.0,2.8,"52,975",tt5697572,"$27,166,770",English,95000000.0,0.0
666,Lost Girls,2020,13 Mar 2020,95 min,"Crime, Drama, Mystery",1 win,67.0,6.1,"22,875",tt3111426,NaN,English,0.0,0.0

In [6]:
#Drop duplicates and check for discrepancies
all_movies.drop_duplicates(subset=["Title"],inplace=True)
print(len(all_movies))
print(all_movies["Title"].nunique())

974
974

In [7]:
#Read netflix csv
netflix = pd.read_csv("resources/NetflixFilms_2018-2022.csv")

In [8]:
#Check for discrepancies
print(len(netflix))
print(netflix["Title"].nunique())

598
598

In [9]:
#Add a format column to netflix data
netflix["Format"] = "netflix"
netflix2 = netflix.loc[:,["Title","Format"]]
netflix2.head()

                         Title   Format
0               The Polka King  netflix
1                 Step Sisters  netflix
2               The Open House  netflix
3  A Futile and Stupid Gesture  netflix
4      The Cloverfield Paradox  netflix

In [10]:
#Merge netflix onto all movies
all_movies_df = pd.merge(all_movies,netflix2,on="Title",how="left")

In [11]:
#Preview the merged DataFrame
all_movies_df.head()

,Title,Year,Released,Runtime,Genre,Awards,Metascore,imdbRating,imdbVotes,imdbID,BoxOffice,Language,budget_max,budget_min,Format
0,Insidious: The Last Key,2018,05 Jan 2018,103 min,"Horror, Mystery, Thriller",6 nominations,49.0,5.7,"62,852",tt5726086,"$67,745,330",English,10000000.0,10000000.0,NaN
1,The Strange Ones,2017,05 Jan 2018,81 min,"Drama, Thriller",5 wins & 11 nominations,57.0,5.1,"2,741",tt6014904,NaN,English,0.0,0.0,NaN
2,Stratton,2017,05 Jan 2018,95 min,"Action, Thriller",NaN,26.0,4.8,"5,398",tt3567666,NaN,English,NaN,NaN,NaN
3,Sweet Country,2017,06 Apr 2018,113 min,"Adventure, Crime, Drama",22 wins & 29 nominations,88.0,6.9,"8,825",tt6958212,"$104,297","English, Aboriginal",0.0,0.0,NaN
4,The Commuter,2018,12 Jan 2018,104 min,"Action, Mystery, Thriller",2 nominations,56.0,6.3,"118,862",tt1590193,"$36,343,858","English, Spanish",30000000.0,30000000.0,NaN

In [12]:
#Classify all non-netflix movies as "others"
all_movies_df["Format"] = all_movies_df["Format"].fillna("others")

In [13]:
#Preview the DataFrame
all_movies_df.head()

,Title,Year,Released,Runtime,Genre,Awards,Metascore,imdbRating,imdbVotes,imdbID,BoxOffice,Language,budget_max,budget_min,Format
0,Insidious: The Last Key,2018,05 Jan 2018,103 min,"Horror, Mystery, Thriller",6 nominations,49.0,5.7,"62,852",tt5726086,"$67,745,330",English,10000000.0,10000000.0,others
1,The Strange Ones,2017,05 Jan 2018,81 min,"Drama, Thriller",5 wins & 11 nominations,57.0,5.1,"2,741",tt6014904,NaN,English,0.0,0.0,others
2,Stratton,2017,05 Jan 2018,95 min,"Action, Thriller",NaN,26.0,4.8,"5,398",tt3567666,NaN,English,NaN,NaN,others
3,Sweet Country,2017,06 Apr 2018,113 min,"Adventure, Crime, Drama",22 wins & 29 nominations,88.0,6.9,"8,825",tt6958212,"$104,297","English, Aboriginal",0.0,0.0,others
4,The Commuter,2018,12 Jan 2018,104 min,"Action, Mystery, Thriller",2 nominations,56.0,6.3,"118,862",tt1590193,"$36,343,858","English, Spanish",30000000.0,30000000.0,others

In [14]:
#Count the number of movies in each "Format"
all_movies_df["Format"].value_counts()

others     868
netflix    106
Name: Format, dtype: int64

In [15]:
#Change format of "Released" and "BoxOffice"
all_movies_df["Released"] = all_movies_df["Released"].astype("datetime64")
all_movies_df["BoxOffice"]  = all_movies_df["BoxOffice"].str.replace("$","")
all_movies_df["BoxOffice"]  = all_movies_df["BoxOffice"].str.replace(",","")
all_movies_df["BoxOffice"] = all_movies_df["BoxOffice"].astype("float")

In [16]:
#Check the data types of each column
all_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 974 entries, 0 to 973
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       974 non-null    object
 1   Year        974 non-null    int64
 2   Released    972 non-null    datetime64[ns]
 3   Runtime     972 non-null    object
 4   Genre       973 non-null    object
 5   Awards      803 non-null    object
 6   Metascore   875 non-null    float64
 7   imdbRating  968 non-null    float64
 8   imdbVotes   969 non-null    object
 9   imdbID      974 non-null    object
 10  BoxOffice   589 non-null    float64
 11  Language    971 non-null    object
 12  budget_max  914 non-null    float64
 13  budget_min  914 non-null    float64
 14  Format      974 non-null    object
dtypes: datetime64[ns](1), float64(5), int64(1), object(8)
memory usage: 121.8+ KB

In [17]:
#Preview the DataFrame
all_movies_df.head()

,Title,Year,Released,Runtime,Genre,Awards,Metascore,imdbRating,imdbVotes,imdbID,BoxOffice,Language,budget_max,budget_min,Format
0,Insidious: The Last Key,2018,2018-01-05,103 min,"Horror, Mystery, Thriller",6 nominations,49.0,5.7,"62,852",tt5726086,67745330.0,English,10000000.0,10000000.0,others
1,The Strange Ones,2017,2018-01-05,81 min,"Drama, Thriller",5 wins & 11 nominations,57.0,5.1,"2,741",tt6014904,NaN,English,0.0,0.0,others
2,Stratton,2017,2018-01-05,95 min,"Action, Thriller",NaN,26.0,4.8,"5,398",tt3567666,NaN,English,NaN,NaN,others
3,Sweet Country,2017,2018-04-06,113 min,"Adventure, Crime, Drama",22 wins & 29 nominations,88.0,6.9,"8,825",tt6958212,104297.0,"English, Aboriginal",0.0,0.0,others
4,The Commuter,2018,2018-01-12,104 min,"Action, Mystery, Thriller",2 nominations,56.0,6.3,"118,862",tt1590193,36343858.0,"English, Spanish",30000000.0,30000000.0,others

In [18]:
#Drop the "Year" and "budget_min"
all_movies_clean = all_movies_df.drop(["Year", "budget_min"], axis=1)

In [19]:
#Preview the DataFrame
all_movies_clean = all_movies_clean.loc[all_movies_clean["Released"]>=('2018-01-01 00:00:00')]
all_movies_clean

,Title,Released,Runtime,Genre,Awards,Metascore,imdbRating,imdbVotes,imdbID,BoxOffice,Language,budget_max,Format
0,Insidious: The Last Key,2018-01-05,103 min,"Horror, Mystery, Thriller",6 nominations,49.0,5.7,"62,852",tt5726086,67745330.0,English,10000000.0,others
1,The Strange Ones,2018-01-05,81 min,"Drama, Thriller",5 wins & 11 nominations,57.0,5.1,"2,741",tt6014904,NaN,English,0.0,others
2,Stratton,2018-01-05,95 min,"Action, Thriller",NaN,26.0,4.8,"5,398",tt3567666,NaN,English,NaN,others
3,Sweet Country,2018-04-06,113 min,"Adventure, Crime, Drama",22 wins & 29 nominations,88.0,6.9,"8,825",tt6958212,104297.0,"English, Aboriginal",0.0,others
4,The Commuter,2018-01-12,104 min,"Action, Mystery, Thriller",2 nominations,56.0,6.3,"118,862",tt1590193,36343858.0,"English, Spanish",30000000.0,others
...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,Free Guy,2021-08-13,115 min,"Action, Adventure, Comedy",Nominated for 1 Oscar. 5 wins & 29 nominations...,62.0,7.1,"382,310",tt6264654,121626598.0,"English, Japanese, German",110000000.0,others
970,Respect,2021-08-13,145 min,"Biography, Drama, Music",3 wins & 40 nominations,61.0,6.6,"16,012",tt2452150,24278399.0,English,0.0,others
971,Beckett,2021-08-13,110 min,"Action, Crime, Drama",1 nomination,52.0,5.7,"27,020",tt10230994,NaN,"English, Greek",0.0,netflix
972,Don't Breathe 2,2021-08-13,98 min,"Action, Crime, Horror",1 nomination,46.0,6.0,"61,405",tt6246322,32712950.0,English,10000000.0,others
973,CODA,2021-08-13,111 min,"Comedy, Drama, Music",Won 3 Oscars. 65 wins & 140 nominations total,72.0,8.0,"143,193",tt10366460,NaN,"American Sign , English",10000000.0,others

In [20]:
#Export to csv
all_movies_clean.to_csv("output_data/all_movies_clean.csv",index=False)

In [21]:
#Read the csv and preview the DataFrame
clean_df = pd.read_csv("output_data/all_movies_clean.csv")
clean_df.head()

,Title,Released,Runtime,Genre,Awards,Metascore,imdbRating,imdbVotes,imdbID,BoxOffice,Language,budget_max,Format
0,Insidious: The Last Key,2018-01-05,103 min,"Horror, Mystery, Thriller",6 nominations,49.0,5.7,"62,852",tt5726086,67745330.0,English,10000000.0,others
1,The Strange Ones,2018-01-05,81 min,"Drama, Thriller",5 wins & 11 nominations,57.0,5.1,"2,741",tt6014904,NaN,English,0.0,others
2,Stratton,2018-01-05,95 min,"Action, Thriller",NaN,26.0,4.8,"5,398",tt3567666,NaN,English,NaN,others
3,Sweet Country,2018-04-06,113 min,"Adventure, Crime, Drama",22 wins & 29 nominations,88.0,6.9,"8,825",tt6958212,104297.0,"English, Aboriginal",0.0,others
4,The Commuter,2018-01-12,104 min,"Action, Mystery, Thriller",2 nominations,56.0,6.3,"118,862",tt1590193,36343858.0,"English, Spanish",30000000.0,others

In [22]:
#Find all rows with "BoxOffice" = NaN
no_box_office = clean_df[clean_df["BoxOffice"].isna()]
no_box_office.head()

,Title,Released,Runtime,Genre,Awards,Metascore,imdbRating,imdbVotes,imdbID,BoxOffice,Language,budget_max,Format
1,The Strange Ones,2018-01-05,81 min,"Drama, Thriller",5 wins & 11 nominations,57.0,5.1,"2,741",tt6014904,NaN,English,0.0,others
2,Stratton,2018-01-05,95 min,"Action, Thriller",NaN,26.0,4.8,"5,398",tt3567666,NaN,English,NaN,others
6,Acts of Violence,2018-01-12,86 min,"Action, Crime, Thriller",NaN,28.0,5.3,"12,708",tt6684714,NaN,English,0.0,others
19,The Cloverfield Paradox,2018-02-04,102 min,"Action, Adventure, Horror",1 nomination,37.0,5.5,"108,105",tt2548396,NaN,"English, Mandarin, German",45000000.0,netflix
20,Bad Apples,2018-02-06,85 min,Horror,NaN,NaN,3.2,"1,792",tt7091300,NaN,English,0.0,others

In [23]:
#Export to csv
no_box_office.to_csv("output_data/no_box_office.csv",index=False)

In [26]:
all_movies_clean["Released"].min()

Timestamp('2018-01-01 00:00:00')